-- Script de Base de Datos para Bolsa de Empleo
-- Ejecutar en Oracle Database

-- Crear Sequences
CREATE SEQUENCE empresa_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE oferente_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE admin_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE puesto_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE caracteristica_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE cv_seq START WITH 1 INCREMENT BY 1;

-- Tabla EMPRESA
CREATE TABLE EMPRESA (
    EMPRESA_ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    RAZON_SOCIAL VARCHAR2(150),
    RFC VARCHAR2(13) UNIQUE,
    TELEFONO VARCHAR2(20),
    DIRECCION VARCHAR2(255),
    CIUDAD VARCHAR2(100),
    ESTADO VARCHAR2(100),
    DESCRIPCION CLOB,
    SITIO_WEB VARCHAR2(200),
    FECHA_REGISTRO TIMESTAMP,
    ACTIVA NUMBER(1) DEFAULT 1
);

-- Tabla OFERENTE
CREATE TABLE OFERENTE (
    OFERENTE_ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    TELEFONO VARCHAR2(20),
    DIRECCION VARCHAR2(255),
    CIUDAD VARCHAR2(100),
    ESTADO VARCHAR2(100),
    PAIS VARCHAR2(100),
    FECHA_NACIMIENTO DATE,
    PROFESION VARCHAR2(150),
    EXPERIENCIA_ANIOS NUMBER(2),
    RESUMEN_PROFESIONAL CLOB,
    FECHA_REGISTRO TIMESTAMP,
    ACTIVO NUMBER(1) DEFAULT 1
);

-- Tabla ADMINISTRADOR
CREATE TABLE ADMINISTRADOR (
    ADMIN_ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROL VARCHAR2(50),
    FECHA_REGISTRO TIMESTAMP,
    ACTIVO NUMBER(1) DEFAULT 1
);

-- Tabla PUESTO
CREATE TABLE PUESTO (
    PUESTO_ID NUMBER PRIMARY KEY,
    TITULO VARCHAR2(150) NOT NULL,
    DESCRIPCION CLOB,
    REQUISITOS CLOB,
    SALARIO_MINIMO NUMBER(10,2),
    SALARIO_MAXIMO NUMBER(10,2),
    MONEDA VARCHAR2(10),
    TIPO_CONTRATO VARCHAR2(50),
    EXPERIENCIA_REQUERIDA VARCHAR2(50),
    NIVEL_EDUCACION VARCHAR2(100),
    UBICACION VARCHAR2(200),
    CIUDAD VARCHAR2(100),
    ESTADO VARCHAR2(100),
    FECHA_PUBLICACION TIMESTAMP,
    FECHA_CIERRE TIMESTAMP,
    ACTIVO NUMBER(1) DEFAULT 1,
    EMPRESA_ID NUMBER NOT NULL,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(EMPRESA_ID)
);

-- Tabla CARACTERISTICA
CREATE TABLE CARACTERISTICA (
    CARACTERISTICA_ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(50),
    NIVEL VARCHAR2(50),
    DESCRIPCION CLOB,
    PUESTO_ID NUMBER,
    OFERENTE_ID NUMBER,
    FOREIGN KEY (PUESTO_ID) REFERENCES PUESTO(PUESTO_ID),
    FOREIGN KEY (OFERENTE_ID) REFERENCES OFERENTE(OFERENTE_ID)
);

-- Tabla CV
CREATE TABLE CV (
    CV_ID NUMBER PRIMARY KEY,
    NOMBRE_ARCHIVO VARCHAR2(255) NOT NULL,
    RUTA_ARCHIVO VARCHAR2(512) NOT NULL,
    TIPO_ARCHIVO VARCHAR2(50),
    TAMANIO NUMBER,
    FECHA_CARGA TIMESTAMP,
    PRINCIPAL NUMBER(1) DEFAULT 0,
    ACTIVO NUMBER(1) DEFAULT 1,
    OFERENTE_ID NUMBER NOT NULL,
    FOREIGN KEY (OFERENTE_ID) REFERENCES OFERENTE(OFERENTE_ID)
);

-- Crear índices
CREATE INDEX idx_empresa_email ON EMPRESA(EMAIL);
CREATE INDEX idx_empresa_rfc ON EMPRESA(RFC);
CREATE INDEX idx_oferente_email ON OFERENTE(EMAIL);
CREATE INDEX idx_puesto_empresa ON PUESTO(EMPRESA_ID);
CREATE INDEX idx_puesto_activo ON PUESTO(ACTIVO);
CREATE INDEX idx_puesto_ciudad ON PUESTO(CIUDAD);
CREATE INDEX idx_caracteristica_puesto ON CARACTERISTICA(PUESTO_ID);
CREATE INDEX idx_caracteristica_oferente ON CARACTERISTICA(OFERENTE_ID);
CREATE INDEX idx_cv_oferente ON CV(OFERENTE_ID);
CREATE INDEX idx_cv_principal ON CV(OFERENTE_ID, PRINCIPAL);

-- Datos de prueba (Opcional)
-- Contraseña para prueba: password123 (codificada con BCrypt)

-- Empresa de prueba
INSERT INTO EMPRESA (EMPRESA_ID, NOMBRE, EMAIL, PASSWORD, RAZON_SOCIAL, RFC, TELEFONO, CIUDAD, ESTADO, FECHA_REGISTRO, ACTIVA)
VALUES (empresa_seq.NEXTVAL, 'Tech Solutions', 'tech@example.com', '$2a$10$slYQmyNdGzin7olVN3p5Be7DFGszHugstufHwAI8/r52.EWyOUHfm', 'Tech Solutions S.A.', 'TSA123456789', '5555-1234', 'Ciudad de México', 'CDMX', SYSDATE, 1);

-- Candidato de prueba
INSERT INTO OFERENTE (OFERENTE_ID, NOMBRE, APELLIDO, EMAIL, PASSWORD, PROFESION, EXPERIENCIA_ANIOS, CIUDAD, ESTADO, FECHA_REGISTRO, ACTIVO)
VALUES (oferente_seq.NEXTVAL, 'Juan', 'Pérez', 'juan@example.com', '$2a$10$slYQmyNdGzin7olVN3p5Be7DFGszHugstufHwAI8/r52.EWyOUHfm', 'Desarrollador Java', 5, 'Ciudad de México', 'CDMX', SYSDATE, 1);

COMMIT;

-- Script de limpieza (para reversión)
-- DROP TABLE CV;
-- DROP TABLE CARACTERISTICA;
-- DROP TABLE PUESTO;
-- DROP TABLE ADMINISTRADOR;
-- DROP TABLE OFERENTE;
-- DROP TABLE EMPRESA;
-- DROP SEQUENCE empresa_seq;
-- DROP SEQUENCE oferente_seq;
-- DROP SEQUENCE admin_seq;
-- DROP SEQUENCE puesto_seq;
-- DROP SEQUENCE caracteristica_seq;
-- DROP SEQUENCE cv_seq;
